name: Real-Time Azure Log Scheduler

on:
  push:
    branches:
      - main
  schedule:
    - cron: '* * * * *'  # Setiap menit
  
  workflow_dispatch:  # Trigger manual

jobs:
  real-time-logger:
    runs-on: ubuntu-latest

    permissions:
      contents: write       # Memberikan izin write ke repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Gunakan token bawaan untuk push

      - name: Setup Git
        run: |
          git config --global user.name "herwinz"
          git config --global user.email "berlianherwindra@gmail.com"

      - name: Generate Log and Push Changes
        run: |
          # Jalankan script log update
          chmod +x scripts/auto_log_update.sh
          ./scripts/auto_log_update.sh

          # Commit dan push perubahan
          CURRENT_TIME=$(date -u +'%Y-%m-%dT%H:%M:%S UTC')
          echo "Committing and pushing changes at $CURRENT_TIME"
          git add logs/azure_monitor_log.json
          git commit -m "Automated Log Update: $CURRENT_TIME" || echo "No changes to commit"
          git push origin main || echo "Push failed, retrying next iteration"

          # Log status
          echo "Log update completed at $CURRENT_TIME"